services:
  - type: web
    name: swingtrace-ai-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120 --limit-max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
